
/home/client/Téléchargements/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner \
  -Dsonar.projectKey=SelectIlLa_Backend \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9100 \
  -Dsonar.login=sqp_19244638af3efeda5642cb483df69edeb690a6d2